/**
 * This class is generated by jOOQ
 */
package me.sunhong.demo.jooq.domain.tables.records;


import javax.annotation.Generated;

import me.sunhong.demo.jooq.domain.tables.Book;
import me.sunhong.demo.jooq.domain.tables.interfaces.IBook;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookRecord extends UpdatableRecordImpl<BookRecord> implements Record5<Integer, Integer, String, Integer, Integer>, IBook {

    private static final long serialVersionUID = 681316487;

    /**
     * Setter for <code>jooq.book.id</code>.
     */
    public BookRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>jooq.book.id</code>.
     */
    @Override
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>jooq.book.author_id</code>.
     */
    public BookRecord setAuthorId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>jooq.book.author_id</code>.
     */
    @Override
    public Integer getAuthorId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>jooq.book.title</code>.
     */
    public BookRecord setTitle(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>jooq.book.title</code>.
     */
    @Override
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>jooq.book.published_in</code>.
     */
    public BookRecord setPublishedIn(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>jooq.book.published_in</code>.
     */
    @Override
    public Integer getPublishedIn() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>jooq.book.language_id</code>.
     */
    public BookRecord setLanguageId(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>jooq.book.language_id</code>.
     */
    @Override
    public Integer getLanguageId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Book.BOOK.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Book.BOOK.AUTHOR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Book.BOOK.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Book.BOOK.PUBLISHED_IN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Book.BOOK.LANGUAGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getAuthorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getPublishedIn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getLanguageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord value2(Integer value) {
        setAuthorId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord value3(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord value4(Integer value) {
        setPublishedIn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord value5(Integer value) {
        setLanguageId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord values(Integer value1, Integer value2, String value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookRecord
     */
    public BookRecord() {
        super(Book.BOOK);
    }

    /**
     * Create a detached, initialised BookRecord
     */
    public BookRecord(Integer id, Integer authorId, String title, Integer publishedIn, Integer languageId) {
        super(Book.BOOK);

        set(0, id);
        set(1, authorId);
        set(2, title);
        set(3, publishedIn);
        set(4, languageId);
    }
}
