/**
 * This class is generated by jOOQ
 */
package me.sunhong.demo.jooq.domain.tables.interfaces;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IAuthor extends Serializable {

    /**
     * Getter for <code>jooq.author.id</code>.
     */
    public Integer getId();

    /**
     * Getter for <code>jooq.author.first_name</code>.
     */
    public String getFirstName();

    /**
     * Getter for <code>jooq.author.last_name</code>.
     */
    public String getLastName();

    /**
     * Getter for <code>jooq.author.date_of_birth</code>.
     */
    public Date getDateOfBirth();

    /**
     * Getter for <code>jooq.author.year_of_birth</code>.
     */
    public Integer getYearOfBirth();

    /**
     * Getter for <code>jooq.author.distinguished</code>.
     */
    public Integer getDistinguished();
}
