/**
 * This class is generated by jOOQ
 */
package me.sunhong.demo.jooq.domain.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IBookStore extends Serializable {

    /**
     * Getter for <code>jooq.book_store.name</code>.
     */
    public String getName();
}
