/**
 * This class is generated by jOOQ
 */
package me.sunhong.demo.jooq.domain.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ILanguage extends Serializable {

    /**
     * Getter for <code>jooq.language.id</code>.
     */
    public Integer getId();

    /**
     * Getter for <code>jooq.language.cd</code>.
     */
    public String getCd();

    /**
     * Getter for <code>jooq.language.description</code>.
     */
    public String getDescription();
}
