/**
 * This class is generated by jOOQ
 */
package me.sunhong.demo.jooq.domain.tables.daos;


import java.sql.Date;
import java.util.List;

import javax.annotation.Generated;

import me.sunhong.demo.jooq.domain.tables.Author;
import me.sunhong.demo.jooq.domain.tables.records.AuthorRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthorDao extends DAOImpl<AuthorRecord, me.sunhong.demo.jooq.domain.tables.pojos.Author, Integer> {

    /**
     * Create a new AuthorDao without any configuration
     */
    public AuthorDao() {
        super(Author.AUTHOR, me.sunhong.demo.jooq.domain.tables.pojos.Author.class);
    }

    /**
     * Create a new AuthorDao with an attached configuration
     */
    public AuthorDao(Configuration configuration) {
        super(Author.AUTHOR, me.sunhong.demo.jooq.domain.tables.pojos.Author.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(me.sunhong.demo.jooq.domain.tables.pojos.Author object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<me.sunhong.demo.jooq.domain.tables.pojos.Author> fetchById(Integer... values) {
        return fetch(Author.AUTHOR.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public me.sunhong.demo.jooq.domain.tables.pojos.Author fetchOneById(Integer value) {
        return fetchOne(Author.AUTHOR.ID, value);
    }

    /**
     * Fetch records that have <code>first_name IN (values)</code>
     */
    public List<me.sunhong.demo.jooq.domain.tables.pojos.Author> fetchByFirstName(String... values) {
        return fetch(Author.AUTHOR.FIRST_NAME, values);
    }

    /**
     * Fetch records that have <code>last_name IN (values)</code>
     */
    public List<me.sunhong.demo.jooq.domain.tables.pojos.Author> fetchByLastName(String... values) {
        return fetch(Author.AUTHOR.LAST_NAME, values);
    }

    /**
     * Fetch records that have <code>date_of_birth IN (values)</code>
     */
    public List<me.sunhong.demo.jooq.domain.tables.pojos.Author> fetchByDateOfBirth(Date... values) {
        return fetch(Author.AUTHOR.DATE_OF_BIRTH, values);
    }

    /**
     * Fetch records that have <code>year_of_birth IN (values)</code>
     */
    public List<me.sunhong.demo.jooq.domain.tables.pojos.Author> fetchByYearOfBirth(Integer... values) {
        return fetch(Author.AUTHOR.YEAR_OF_BIRTH, values);
    }

    /**
     * Fetch records that have <code>distinguished IN (values)</code>
     */
    public List<me.sunhong.demo.jooq.domain.tables.pojos.Author> fetchByDistinguished(Integer... values) {
        return fetch(Author.AUTHOR.DISTINGUISHED, values);
    }
}
