/**
 * This class is generated by jOOQ
 */
package me.sunhong.demo.jooq.domain.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import me.sunhong.demo.jooq.domain.tables.BookToBookStore;
import me.sunhong.demo.jooq.domain.tables.records.BookToBookStoreRecord;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookToBookStoreDao extends DAOImpl<BookToBookStoreRecord, me.sunhong.demo.jooq.domain.tables.pojos.BookToBookStore, Record2<String, Integer>> {

    /**
     * Create a new BookToBookStoreDao without any configuration
     */
    public BookToBookStoreDao() {
        super(BookToBookStore.BOOK_TO_BOOK_STORE, me.sunhong.demo.jooq.domain.tables.pojos.BookToBookStore.class);
    }

    /**
     * Create a new BookToBookStoreDao with an attached configuration
     */
    public BookToBookStoreDao(Configuration configuration) {
        super(BookToBookStore.BOOK_TO_BOOK_STORE, me.sunhong.demo.jooq.domain.tables.pojos.BookToBookStore.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<String, Integer> getId(me.sunhong.demo.jooq.domain.tables.pojos.BookToBookStore object) {
        return compositeKeyRecord(object.getName(), object.getBookId());
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<me.sunhong.demo.jooq.domain.tables.pojos.BookToBookStore> fetchByName(String... values) {
        return fetch(BookToBookStore.BOOK_TO_BOOK_STORE.NAME, values);
    }

    /**
     * Fetch records that have <code>book_id IN (values)</code>
     */
    public List<me.sunhong.demo.jooq.domain.tables.pojos.BookToBookStore> fetchByBookId(Integer... values) {
        return fetch(BookToBookStore.BOOK_TO_BOOK_STORE.BOOK_ID, values);
    }

    /**
     * Fetch records that have <code>stock IN (values)</code>
     */
    public List<me.sunhong.demo.jooq.domain.tables.pojos.BookToBookStore> fetchByStock(Integer... values) {
        return fetch(BookToBookStore.BOOK_TO_BOOK_STORE.STOCK, values);
    }
}
