/**
 * This class is generated by jOOQ
 */
package me.sunhong.demo.jooq.domain.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import me.sunhong.demo.jooq.domain.tables.Book;
import me.sunhong.demo.jooq.domain.tables.records.BookRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookDao extends DAOImpl<BookRecord, me.sunhong.demo.jooq.domain.tables.pojos.Book, Integer> {

    /**
     * Create a new BookDao without any configuration
     */
    public BookDao() {
        super(Book.BOOK, me.sunhong.demo.jooq.domain.tables.pojos.Book.class);
    }

    /**
     * Create a new BookDao with an attached configuration
     */
    public BookDao(Configuration configuration) {
        super(Book.BOOK, me.sunhong.demo.jooq.domain.tables.pojos.Book.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(me.sunhong.demo.jooq.domain.tables.pojos.Book object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<me.sunhong.demo.jooq.domain.tables.pojos.Book> fetchById(Integer... values) {
        return fetch(Book.BOOK.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public me.sunhong.demo.jooq.domain.tables.pojos.Book fetchOneById(Integer value) {
        return fetchOne(Book.BOOK.ID, value);
    }

    /**
     * Fetch records that have <code>author_id IN (values)</code>
     */
    public List<me.sunhong.demo.jooq.domain.tables.pojos.Book> fetchByAuthorId(Integer... values) {
        return fetch(Book.BOOK.AUTHOR_ID, values);
    }

    /**
     * Fetch records that have <code>title IN (values)</code>
     */
    public List<me.sunhong.demo.jooq.domain.tables.pojos.Book> fetchByTitle(String... values) {
        return fetch(Book.BOOK.TITLE, values);
    }

    /**
     * Fetch records that have <code>published_in IN (values)</code>
     */
    public List<me.sunhong.demo.jooq.domain.tables.pojos.Book> fetchByPublishedIn(Integer... values) {
        return fetch(Book.BOOK.PUBLISHED_IN, values);
    }

    /**
     * Fetch records that have <code>language_id IN (values)</code>
     */
    public List<me.sunhong.demo.jooq.domain.tables.pojos.Book> fetchByLanguageId(Integer... values) {
        return fetch(Book.BOOK.LANGUAGE_ID, values);
    }
}
