/**
 * This class is generated by jOOQ
 */
package me.sunhong.demo.jooq.domain.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import me.sunhong.demo.jooq.domain.tables.Language;
import me.sunhong.demo.jooq.domain.tables.records.LanguageRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LanguageDao extends DAOImpl<LanguageRecord, me.sunhong.demo.jooq.domain.tables.pojos.Language, Integer> {

    /**
     * Create a new LanguageDao without any configuration
     */
    public LanguageDao() {
        super(Language.LANGUAGE, me.sunhong.demo.jooq.domain.tables.pojos.Language.class);
    }

    /**
     * Create a new LanguageDao with an attached configuration
     */
    public LanguageDao(Configuration configuration) {
        super(Language.LANGUAGE, me.sunhong.demo.jooq.domain.tables.pojos.Language.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(me.sunhong.demo.jooq.domain.tables.pojos.Language object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<me.sunhong.demo.jooq.domain.tables.pojos.Language> fetchById(Integer... values) {
        return fetch(Language.LANGUAGE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public me.sunhong.demo.jooq.domain.tables.pojos.Language fetchOneById(Integer value) {
        return fetchOne(Language.LANGUAGE.ID, value);
    }

    /**
     * Fetch records that have <code>cd IN (values)</code>
     */
    public List<me.sunhong.demo.jooq.domain.tables.pojos.Language> fetchByCd(String... values) {
        return fetch(Language.LANGUAGE.CD, values);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<me.sunhong.demo.jooq.domain.tables.pojos.Language> fetchByDescription(String... values) {
        return fetch(Language.LANGUAGE.DESCRIPTION, values);
    }
}
