/**
 * This class is generated by jOOQ
 */
package me.sunhong.demo.jooq.domain;


import javax.annotation.Generated;

import me.sunhong.demo.jooq.domain.tables.Author;
import me.sunhong.demo.jooq.domain.tables.Book;
import me.sunhong.demo.jooq.domain.tables.BookStore;
import me.sunhong.demo.jooq.domain.tables.BookToBookStore;
import me.sunhong.demo.jooq.domain.tables.Language;


/**
 * Convenience access to all tables in jooq
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooq.author</code>.
     */
    public static final Author AUTHOR = me.sunhong.demo.jooq.domain.tables.Author.AUTHOR;

    /**
     * The table <code>jooq.book</code>.
     */
    public static final Book BOOK = me.sunhong.demo.jooq.domain.tables.Book.BOOK;

    /**
     * The table <code>jooq.book_store</code>.
     */
    public static final BookStore BOOK_STORE = me.sunhong.demo.jooq.domain.tables.BookStore.BOOK_STORE;

    /**
     * The table <code>jooq.book_to_book_store</code>.
     */
    public static final BookToBookStore BOOK_TO_BOOK_STORE = me.sunhong.demo.jooq.domain.tables.BookToBookStore.BOOK_TO_BOOK_STORE;

    /**
     * The table <code>jooq.language</code>.
     */
    public static final Language LANGUAGE = me.sunhong.demo.jooq.domain.tables.Language.LANGUAGE;
}
