/**
 * This class is generated by jOOQ
 */
package me.sunhong.demo.jooq.domain.tables.pojos;


import java.sql.Date;

import javax.annotation.Generated;

import me.sunhong.demo.jooq.domain.tables.interfaces.IAuthor;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Author implements IAuthor {

    private static final long serialVersionUID = -134080875;

    private final Integer id;
    private final String  firstName;
    private final String  lastName;
    private final Date    dateOfBirth;
    private final Integer yearOfBirth;
    private final Integer distinguished;

    public Author(Author value) {
        this.id = value.id;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.dateOfBirth = value.dateOfBirth;
        this.yearOfBirth = value.yearOfBirth;
        this.distinguished = value.distinguished;
    }

    public Author(
        Integer id,
        String  firstName,
        String  lastName,
        Date    dateOfBirth,
        Integer yearOfBirth,
        Integer distinguished
    ) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.dateOfBirth = dateOfBirth;
        this.yearOfBirth = yearOfBirth;
        this.distinguished = distinguished;
    }

    @Override
    public Integer getId() {
        return this.id;
    }

    @Override
    public String getFirstName() {
        return this.firstName;
    }

    @Override
    public String getLastName() {
        return this.lastName;
    }

    @Override
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }

    @Override
    public Integer getYearOfBirth() {
        return this.yearOfBirth;
    }

    @Override
    public Integer getDistinguished() {
        return this.distinguished;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Author (");

        sb.append(id);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(dateOfBirth);
        sb.append(", ").append(yearOfBirth);
        sb.append(", ").append(distinguished);

        sb.append(")");
        return sb.toString();
    }
}
