/**
 * This class is generated by jOOQ
 */
package me.sunhong.demo.jooq.domain.tables.pojos;


import javax.annotation.Generated;

import me.sunhong.demo.jooq.domain.tables.interfaces.IBook;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Book implements IBook {

    private static final long serialVersionUID = 135772485;

    private final Integer id;
    private final Integer authorId;
    private final String  title;
    private final Integer publishedIn;
    private final Integer languageId;

    public Book(Book value) {
        this.id = value.id;
        this.authorId = value.authorId;
        this.title = value.title;
        this.publishedIn = value.publishedIn;
        this.languageId = value.languageId;
    }

    public Book(
        Integer id,
        Integer authorId,
        String  title,
        Integer publishedIn,
        Integer languageId
    ) {
        this.id = id;
        this.authorId = authorId;
        this.title = title;
        this.publishedIn = publishedIn;
        this.languageId = languageId;
    }

    @Override
    public Integer getId() {
        return this.id;
    }

    @Override
    public Integer getAuthorId() {
        return this.authorId;
    }

    @Override
    public String getTitle() {
        return this.title;
    }

    @Override
    public Integer getPublishedIn() {
        return this.publishedIn;
    }

    @Override
    public Integer getLanguageId() {
        return this.languageId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Book (");

        sb.append(id);
        sb.append(", ").append(authorId);
        sb.append(", ").append(title);
        sb.append(", ").append(publishedIn);
        sb.append(", ").append(languageId);

        sb.append(")");
        return sb.toString();
    }
}
